name: kodebackend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Ensure it runs on a valid GitHub Actions runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build the JAR file
        run: |
          chmod +x mvnw  # Ensure Maven wrapper is executable
          ./mvnw clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/kodebackend:latest .
          docker push "${{ secrets.DOCKER_USERNAME }}"/kodebackend:latest
      - name: Trivy Scanning 
        run: |
          sudo snap install trivy
          trivy image "${{ secrets.DOCKER_USERNAME}}"/kodebackend:latest
